spring.application.name=ShafwahBE

#spring.security.user.name=baobaojingyi
#spring.security.user.password=kimchaehyunnie

superadmin.password=kimchaehyunnie
jwt.secret=baobao-jingyi-wo-de-ai-ren-wo-xiang-ni
jwt.expiration-ms=604800000

spring.datasource.url=jdbc:postgresql://localhost:5000/shafwah_be
spring.datasource.username=postgres
spring.datasource.password=kimchaehyunnie

#Hibernate akan otomatis bikin tabel kalau belum ada.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9999
